// Firebase configuration for HapagPamana.
//
// Values come from the Firebase console (project hapagpamana-39687):
//   · Android  → google-services.json (package com.HapagPamana)
//   · Web      → Admin/firebase-config.js
//   · iOS      → ios/Runner/GoogleService-Info.plist (bundle com.hapag.pamana)
// macOS isn't registered — add it in the console and fill in the blanks
// below if/when the app ships there.
//
// Hand-written rather than generated by the FlutterFire CLI; keep in step with
// the console if the registration changes.
//
// The apiKey on each is read from .env (see env.dart) rather than typed here
// — not because it's an access-granting secret (Firebase's client apiKey
// isn't; access is Firestore/Auth security rules, not this key), but so
// every project credential lives in one place. [Env.load] must have already
// run by the time [currentPlatform] is read — see main().
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform — register the platform in the Firebase '
          'console and add its options here.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: Env.firebaseAndroidApiKey,
        appId: '1:369246306524:android:f21dc358f5b63b8db97419',
        messagingSenderId: '369246306524',
        projectId: 'hapagpamana-39687',
        storageBucket: 'hapagpamana-39687.firebasestorage.app',
      );

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: Env.firebaseWebApiKey,
        appId: '1:369246306524:web:f3a4b31aa39e8370b97419',
        messagingSenderId: '369246306524',
        projectId: 'hapagpamana-39687',
        authDomain: 'hapagpamana-39687.firebaseapp.com',
        storageBucket: 'hapagpamana-39687.firebasestorage.app',
        measurementId: 'G-S4PRHFNPWH',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: Env.firebaseIosApiKey,
        appId: '1:369246306524:ios:248b57902d96c9d6b97419',
        messagingSenderId: '369246306524',
        projectId: 'hapagpamana-39687',
        storageBucket: 'hapagpamana-39687.firebasestorage.app',
        iosBundleId: 'com.hapag.pamana',
      );
}
