// Firebase configuration for HapagPamana.
//
// Values come from the Firebase console (project hapagpamana-39687):
//   · Android  → google-services.json (package com.HapagPamana)
//   · Web      → Admin/firebase-config.js
// iOS/macOS aren't registered yet — add them in the console and fill in the
// blanks below if/when the app ships to Apple platforms.
//
// Hand-written rather than generated by the FlutterFire CLI; keep in step with
// the console if the registration changes.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform — register the platform in the Firebase '
          'console and add its options here.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbKQtqZLKDKF5QxC-BeNkIBtlzAdmC_Ho',
    appId: '1:369246306524:android:f21dc358f5b63b8db97419',
    messagingSenderId: '369246306524',
    projectId: 'hapagpamana-39687',
    storageBucket: 'hapagpamana-39687.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokGGoVNFZIJujMFC52yzkOTnG_sxeT4E',
    appId: '1:369246306524:web:f3a4b31aa39e8370b97419',
    messagingSenderId: '369246306524',
    projectId: 'hapagpamana-39687',
    authDomain: 'hapagpamana-39687.firebaseapp.com',
    storageBucket: 'hapagpamana-39687.firebasestorage.app',
    measurementId: 'G-S4PRHFNPWH',
  );
}
